# Generated by Django 2.2.3 on 2019-09-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0003_auto_20190821_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcourse',
            name='preview',
            field=models.ImageField(null=True, upload_to='course/<django.db.models.fields.CharField>/preview/'),
        ),
        migrations.AlterField(
            model_name='schoolcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')},
                                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
