# Generated by Django 2.2.3 on 2019-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0004_auto_20190902_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcourse',
            name='preview',
            field=models.ImageField(null=True, upload_to='courses/preview/'),
        ),
    ]
