# Generated by Django 2.2.3 on 2019-09-11 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0005_auto_20190910_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'SFile', 'verbose_name_plural': 'SFiles'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'SImage', 'verbose_name_plural': 'SImages'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'SText', 'verbose_name_plural': 'STexts'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'SVideo', 'verbose_name_plural': 'SVideos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='school/videos'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='school/files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='school/images'),
        ),
        migrations.AlterField(
            model_name='schoolcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('stext', 'svideo', 'simage', 'sfile')},
                                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
