# Generated by Django 2.2.3 on 2019-09-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0006_auto_20190923_2227'),
        ('school_courses', '0008_auto_20190924_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolsubject',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='schools.School'),
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects',
                                    to='schools.School'),
        ),
    ]
