# Generated by Django 2.2.3 on 2019-10-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0009_auto_20190926_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolcourse',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolcourse',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
