# Generated by Django 2.2.3 on 2019-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0010_auto_20191005_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsfile',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsimage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsvideo',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sfile',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='simage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='svideo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
