# Generated by Django 2.2.3 on 2019-10-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('school_courses', '0014_auto_20191019_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschoolcourse',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolcourse',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
