# Generated by Django 2.2.3 on 2019-08-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20190817_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'SchoolStudent'), ('teacher', 'Teacher'), ('school', 'School'),
                                            ('curator', 'Curator'), ('Marketer', 'Editor'),
                                            ('super admin', 'Super Admin')], max_length=10,
                                   verbose_name='Account Type'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curator',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator',
                                    to='accounts.SuperAdmin'),
        ),
        migrations.AddField(
            model_name='editor',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor',
                                    to='accounts.SuperAdmin'),
        ),
    ]
