# Generated by Django 2.2.3 on 2019-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auto_20190822_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'SchoolStudent'), ('teacher', 'Teacher'), ('school', 'School'),
                                            ('curator', 'Curator'), ('editor', 'Editor'),
                                            ('super admin', 'Super Admin'), ('admin', 'Admin')], max_length=11,
                                   verbose_name='Account Type'),
        ),
    ]
