# Generated by Django 2.2.3 on 2019-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts',
         '0008_historicalcurator_historicaleditor_historicalgrade_historicalstudent_historicalsuperadmin_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcurator',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaleditor',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalgrade',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsuperadmin',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
