# Generated by Django 2.2.3 on 2019-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_auto_20190910_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='Avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/Users/avatar/%Y/%m/%d'),
        ),
    ]
