# Generated by Django 2.2.3 on 2019-09-11 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0011_auto_20190911_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Avatar',
            new_name='avatar',
        ),
    ]
