# Generated by Django 2.2.3 on 2019-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0014_auto_20190926_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_curator',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_marketer',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_school',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_curator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_marketer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
