# Generated by Django 2.2.3 on 2019-09-28 17:56

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0015_auto_20190928_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='curator',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcurator',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
    ]
