# Generated by Django 2.2.3 on 2019-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0016_auto_20190928_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicaleditor',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalsuperadmin',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
    ]
