# Generated by Django 2.2.3 on 2019-10-10 04:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0018_auto_20191005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='account_type',
            field=models.CharField(
                choices=[('student', 'SchoolStudent'), ('aonestudent', 'AoneStudent'), ('teacher', 'Teacher'),
                         ('school', 'School'), ('curator', 'Curator'), ('editor', 'Editor'),
                         ('super admin', 'Super Admin'), ('marketer', 'Marketer'), ('admin', 'Admin')], max_length=11,
                verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(
                choices=[('student', 'SchoolStudent'), ('aonestudent', 'AoneStudent'), ('teacher', 'Teacher'),
                         ('school', 'School'), ('curator', 'Curator'), ('editor', 'Editor'),
                         ('super admin', 'Super Admin'), ('marketer', 'Marketer'), ('admin', 'Admin')], max_length=11,
                verbose_name='Account Type'),
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer',
                                            to='accounts.SuperAdmin')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_profile',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMarketer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                            to='accounts.SuperAdmin')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical marketer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
