# Generated by Django 2.2.3 on 2019-08-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='quiz',
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='aonebrains_quiz.Quiz', verbose_name='Quiz'),
            preserve_default=False,
        ),
    ]
