# Generated by Django 2.2.3 on 2019-09-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_quiz', '0003_auto_20190824_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], default='content',
                                   help_text='The order in which multichoice                     answer options are displayed                     to the user',
                                   max_length=30, null=True, verbose_name='Answer Order'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='aonebrains_quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student',
                                       verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answers_at_end',
            field=models.BooleanField(default=True,
                                      help_text='Correct answer is NOT shown after question. Answers displayed at the end.',
                                      verbose_name='Answers at end'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student',
                                    verbose_name='Student'),
        ),
    ]
