# Generated by Django 2.2.3 on 2019-10-20 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_quiz',
         '0005_historicalanswer_historicalmcqquestion_historicalprogress_historicalquiz_historicalsitting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aonebrains_quiz.MCQQuestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aonebrains_courses.OpenCourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='questions', to='aonebrains_quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student',
                                       verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='aonebrains_courses.OpenCourse', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aonebrains_quiz.Quiz',
                                    verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student',
                                    verbose_name='Student'),
        ),
    ]
