# Generated by Django 2.2.3 on 2019-09-11 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0003_school_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
    ]
