# Generated by Django 2.2.3 on 2019-09-24 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0005_auto_20190914_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='school_student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
