# Generated by Django 2.2.3 on 2019-10-20 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0008_auto_20191019_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools',
                                    to='accounts.Marketer'),
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='school_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students',
                                    to='schools.School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='school_student_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='teacher_class', to='accounts.Grade'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers',
                                    to='schools.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
