# Generated by Django 2.2.3 on 2020-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20191019_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
