# Generated by Django 2.2.3 on 2020-03-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20200217_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolstudent',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
