# Generated by Django 2.2.3 on 2019-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0005_auto_20190824_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencourse',
            name='preview',
            field=models.ImageField(null=True, upload_to='course/<django.db.models.fields.CharField>/preview/'),
        ),
    ]
