# Generated by Django 2.2.3 on 2019-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0006_opencourse_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencourse',
            name='preview',
            field=models.ImageField(null=True, upload_to='courses/preview/'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='school_students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to='schools.SchoolStudent'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='accounts.Student'),
        ),
    ]
