# Generated by Django 2.2.3 on 2019-09-11 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0008_auto_20190911_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afile',
            options={'verbose_name': 'AFile', 'verbose_name_plural': 'AFiles'},
        ),
        migrations.AlterModelOptions(
            name='aimage',
            options={'verbose_name': 'AImage', 'verbose_name_plural': 'AImages'},
        ),
        migrations.AlterModelOptions(
            name='atext',
            options={'verbose_name': 'AText', 'verbose_name_plural': 'ATexts'},
        ),
        migrations.AlterModelOptions(
            name='avideo',
            options={'verbose_name': 'AVideo', 'verbose_name_plural': 'AVideos'},
        ),
    ]
