# Generated by Django 2.2.3 on 2019-10-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses',
         '0011_historicalafile_historicalaimage_historicalatext_historicalavideo_historicalopencontent_historicalop'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopencourse',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opencourse',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
