# Generated by Django 2.2.3 on 2019-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0012_auto_20191005_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='afile',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aimage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atext',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='atext',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='atext',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='avideo',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalafile',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalaimage',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalatext',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalatext',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalatext',
            name='video',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalavideo',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='atext',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalatext',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
