# Generated by Django 2.2.3 on 2019-10-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0014_auto_20191013_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencourse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Curator'),
        ),
    ]
