# Generated by Django 2.2.3 on 2019-10-20 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0015_auto_20191017_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afile',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='afile_related', to='accounts.Curator'),
        ),
        migrations.AlterField(
            model_name='aimage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='aimage_related', to='accounts.Curator'),
        ),
        migrations.AlterField(
            model_name='atext',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='atext_related', to='accounts.Curator'),
        ),
        migrations.AlterField(
            model_name='avideo',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='avideo_related', to='accounts.Curator'),
        ),
        migrations.AlterField(
            model_name='opencontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('atext', 'avideo', 'aimage', 'afile')}, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='opencontent',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents',
                                    to='aonebrains_courses.OpenModule'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses',
                                    to='accounts.SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Curator'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Grade'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses',
                                    to='aonebrains_courses.OpenSubject'),
        ),
        migrations.AlterField(
            model_name='openmodule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules',
                                    to='aonebrains_courses.OpenCourse'),
        ),
    ]
