# Generated by Django 2.2.3 on 2019-10-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aonebrains_courses', '0016_auto_20191019_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afile',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='afile_related', to='accounts.Curator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimage',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='aimage_related', to='accounts.Curator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atext',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='atext_related', to='accounts.Curator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avideo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='avideo_related', to='accounts.Curator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opencontent',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('atext', 'avideo', 'aimage', 'afile')},
                                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opencontent',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents',
                                    to='aonebrains_courses.OpenModule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses',
                                    to='accounts.SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Curator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Grade'),
        ),
        migrations.AlterField(
            model_name='opencourse',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses',
                                    to='aonebrains_courses.OpenSubject'),
        ),
        migrations.AlterField(
            model_name='openmodule',
            name='course',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                    to='aonebrains_courses.OpenCourse'),
            preserve_default=False,
        ),
    ]
